### ISSUE TITLE
Not sure how to import the output into blender

### ISSUE THREAD

**Issue by a3dzzm** [eArmada8/gust_stuff#2]
At my wit's end. I have 3dmigoto installed in blender but can't figure out how to get the output from g1m export into blender. Help would be appreciated!

**Comment by eArmada8** [comment]
Sorry, I haven't gotten around to improving the documentation yet but it is on the to-do list.

In the meantime, assuming that the script actually worked for you and you have the .fmt/.ib/.vb files:

1. [Install and activate the plug-in](https://www.youtube.com/watch?v=z2nvJzkwHHQ&t=375s)
2. File Menu -> Import -> 3dmigoto raw buffers (.vb + .ib) - *if you do not see this option then step 1 was not done correctly; please be sure to watch the video carefully*

I am going to close this, as it is not actually an issue with my code.  You can still respond to this issue and I will still get notifications, although I generally do not give tech support, sorry.  I will write more documentation soon(ish)!

**Comment by a3dzzm** [comment]
That's helpful, thank you! Sorry for bombarding the issues section.

**Comment by eArmada8** [comment]
Not at all!  I know I need more documentation.  It's just my attention is a bit scattered.

**Comment by eArmada8** [comment]
I’ve started writing documentation, here is the landing page of the wiki! https://github.com/eArmada8/gust_stuff/wiki
