### ISSUE TITLE
Marvel Ultimate Alliance 3 VB/IB files.

### ISSUE THREAD

**Issue by Charsles** [eArmada8/gust_stuff#4]
hey there, i'm me again... i don't know if the problem is with your exporter or the 3dmigoto blender plugin but the MUA3 models don't get the bones/vertex renamed when i import to blender. i tried the method of changing the BLENDINDICES in the fmt file to UNKNOWN but now it doesn't load any vertex/bone names. also, when i export the files, i don't even get the vgmap file too

this is how it looks after changing the fmt file options
![imagem_2024-09-17_110053510](https://github.com/user-attachments/assets/c4aa6c3a-1355-4dcb-85e9-72c34570ab42)

and this is how it normally looks, wich is totally messed up and i don't know what to do anymore since i can't mod the game like this.

![image](https://github.com/user-attachments/assets/3e0b69a1-e9eb-42e4-a47a-f49cc0d3aa98)
![image](https://github.com/user-attachments/assets/fc6a4602-a2f7-4e5f-9357-41614b44b72b)
![image](https://github.com/user-attachments/assets/326a918a-f643-4221-868c-7bc557b361c9)
![image](https://github.com/user-attachments/assets/6f4e80a9-be9b-457a-9839-572714ea5e26)

it's almost like the meshes are telling theirself that they have separated bones for each one of them and all of them starts with 0. like i said, i don't know if the problem is with the G1M unpacker or the Blender plugin but would you mind helping me fix this plz? i'm having a really hard time trying to understand. i even tried to use the "g1m_to_basic_gltf" script but when the process ends and i try to open the model on blender, i get this:
![image](https://github.com/user-attachments/assets/b597f321-fa1b-49ba-a73a-e00eccafd32a)

i will be leaving the G1M and the VB/IB files if you want to check them out
https://www.mediafire.com/file/rrgc27100lv0fgj/0005_WIDOW_mdl.rar/file

**Comment by eArmada8** [comment]
The G1M format does not have any bone names in it.  Gust (Atelier/BR) games specifically store them in a file called Oid, but other game studios that I've come across do not give us bone names at all.  Regardless, they are not inside the G1M file - inside the file the bones are indexed (essentially you can think of indexed as numbered).

For example, this is the contents of pc00a_model.elixir.gz, as reported by Gust Tools:
```
{
    "json_version": 0x1,
    "name": "pc00a_model.elixir.gz",
    "compressed": true,
    "flags": 0xa,
    "files": [
        "PC00A_MODEL.g1m",
        "PC00A_MODEL_default.g1m",
        "PC00A_MODELOid.bin",
        "PC00A_MODEL.swg"
    ]
}
```
The first file is the model alone, the second file has the skeleton, the third is a list of bone names, and the fourth is some sort of physics data.  So if you want to have bone names, you will have to find the Oid file.

For reference, ProjectG1M states that [there are two types of Oid](https://github.com/Joschuka/Project-G1M/blob/main/Source/Public/Oid.h), and I believe my script can successfully decode them both.  I did not find any information on alternate ways to store bone names at [THRG](https://github.com/three-houses-research-team/010-binary-templates/tree/master/Model%20related%20formats).

**Comment by Charsles** [comment]
i don't think we have this type of file on MUA3 models. i've exported a lot of models before and none of them gave me this file. maybe could it be one of those .bin? every model has and i noticed that the Oid in the file above is in .bin format too, maybe if i rename the file could work? 

![imagem_2024-09-17_125840529](https://github.com/user-attachments/assets/63f4de18-0070-44d8-8f0b-c9c1d2f5a5a3)

**Comment by eArmada8** [comment]
Open any files you think might be an oid file in a hex editor, it will be very obvious.  This is what PC00A_MODELOid.bin looks like:

```
HeaderCharaOidObjectID:PC00A_MODEL10,root
1,SK_Skeleton	2,SK_Hips3,SK_Spine014,SK_Spine02	5,SK_Neck	6,SK_Head7,SK_L_UpLeg8,SK_R_UpLeg
9,SK_L_Leg10,SK_R_Leg11,SK_L_Foot12,SK_R_Foot13,SK_L_Toes14,SK_R_Toes15,SK_L_Shoulder16,SK_R_Shoulder17,SK_L_Arm18,SK_R_Arm19,SK_L_ForeArm20,SK_R_ForeArm21,SK_L_Hand22,SK_R_Hand23,SK_L_Weapon24,SK_R_Weapon50,
```

**Comment by eArmada8** [comment]
Also, the gltf script does not support extended bonemaps, and I have no plan to add support since no atelier games use them.  Please use [Project G1M](https://github.com/Joschuka/Project-G1M) to get a gltf file.

**Comment by Charsles** [comment]
oh yeah, i totally forgot to send the skeleton model so you could check it out, sorry about that! here all of the model folder
0004.g1m is the skeleton
0005.g1m is the base model
0006 until 0009 is the other models.

can you try to load the model on blender? 

https://www.mediafire.com/file/0blb8bt62l050lg/0005_WIDOW_mdl.rar/file

**Comment by eArmada8** [comment]
Ok, I fixed a few bugs, I think things are working moreso as intended now.  Try [v1.3.11](https://github.com/eArmada8/gust_stuff/releases/tag/v1.3.11).  Note that without the Oid file, you will still have generic bone names, but at least now they are consistent across the bone palettes.  I fixed a few small issues with the glTF exporter as well.

**Comment by Charsles** [comment]
i will be closing this issue since it's not actually an issue, it's the game that don't has this file but thanks for the attention and for updating the tool once again!

**Comment by Charsles** [comment]
i will be closing this issue since it's not actually an issue, it's the game that don't has this file but thanks for the attention and for updating the tool once again!

**Comment by Charsles** [comment]
hey there @eArmada8, this is not an issue but a invitation. do you have discord? if so, would you mind helping us from the MUA3 community to create a script? we are using yours as base. you don't need to do the work, only to explain things for us, guiding us. pleeease. 

here is the link
https://discord.gg/QjCWPSHx
